# Root Terragrunt configuration for the kubernetes-terraform modules.
#
# Inputs defined here are passed to every child module automatically.
# Module-specific vars (versions, secrets) live in each module's terraform.tfvars
# and secrets.auto.tfvars.
#
# Apply everything:
#   cd kubernetes-terraform && terragrunt run --all apply
#
# Apply a single module:
#   cd kubernetes-terraform/core && terragrunt apply

locals {
  kubeconfig_path = "~/.kube/config"
}

# onepassword_vault_id is deliberately not set here — it comes from TF_VAR_onepassword_vault_id,
# injected by `op run --environment` (see Makefile), same pattern as proxmox-terraform's
# TF_VAR_onepassword_bootstrap_vault_id.
inputs = {
  kubeconfig_path = local.kubeconfig_path
}

# Each module gets its own state file under .terraform-state/
# Paths: .terraform-state/core/, .terraform-state/vault/, .terraform-state/argocd/
remote_state {
  backend = "local"
  config = {
    path = "${get_parent_terragrunt_dir()}/.terraform-state/${path_relative_to_include()}/terraform.tfstate"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# Shared variable declarations — emitted as shared_vars.tf into every child module.
# Only variables actually used somewhere today live here — add more back as new
# modules genuinely need them, rather than pre-declaring for a design that isn't built yet.
generate "shared_vars" {
  path      = "shared_vars.tf"
  if_exists = "overwrite"
  contents  = <<-EOF
    # Generated by root terragrunt.hcl — do not edit directly.
    # Module-specific variables belong in each module's vars.tf.

    variable "kubeconfig_path" {
      description = "Path to write a local kubeconfig to, for kubectl/talosctl convenience (e.g. ~/.kube/config). Left unset by default so nothing writes a file under CI, where it wouldn't persist to be useful anyway — opt in locally via TF_VAR_kubeconfig_path."
      type        = string
      default     = null
    }

    variable "onepassword_vault_id" {
      description = "UUID of the 1Password vault dedicated to this cluster's secrets."
      type        = string
    }
  EOF
}

# Shared provider version constraints — emitted as versions.tf into every child module.
# This is the single source of truth for all provider versions.
#
# The onepassword provider is declared here even though only secrets/ uses it (as a writer)
# — apps/argocd's ExternalSecrets reference 1Password items by string key, not through this
# provider. Terraform only initializes a provider when a provider {} block is configured in
# that module, so non-consuming modules incur no runtime cost from the declaration.
#
# Renovate note: versions here are picked up by the custom regex manager in renovate.json
# that scans terragrunt.hcl files. The generated versions.tf files are gitignored.
generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Generated by root terragrunt.hcl — do not edit directly.
    # Update provider versions in kubernetes-terraform/root.hcl instead.
    terraform {
      required_providers {
        helm = {
          source  = "hashicorp/helm"
          version = "~> 3.3.0"  # renovate: datasource=terraform-provider depName=hashicorp/helm
        }
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 3.2.0"  # renovate: datasource=terraform-provider depName=hashicorp/kubernetes
        }
        onepassword = {
          source  = "1Password/onepassword"
          version = "~> 3.3"  # renovate: datasource=terraform-provider depName=1Password/onepassword
        }
        talos = {
          source  = "registry.terraform.io/siderolabs/talos"
          version = "0.12.0-beta.0"  # renovate: datasource=terraform-provider depName=siderolabs/talos
        }
        local = {
          source  = "hashicorp/local"
          version = "~> 2.9"  # renovate: datasource=terraform-provider depName=hashicorp/local
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 3.8"  # renovate: datasource=terraform-provider depName=hashicorp/random
        }
        null = {
          source  = "hashicorp/null"
          version = "~> 3.2"  # renovate: datasource=terraform-provider depName=hashicorp/null
        }
      }
    }
  EOF
}
