# Root Terragrunt configuration for the kubernetes-terraform modules.
#
# Inputs defined here are passed to every child module automatically.
# Module-specific vars (versions, secrets) live in each module's terraform.tfvars
# and secrets.auto.tfvars. Hostnames are derived from var.domain in each module's
# locals.tf rather than being passed as separate variables.
#
# Apply everything:
#   cd kubernetes-terraform && terragrunt run --all apply
#
# Apply a single module:
#   cd kubernetes-terraform/core && terragrunt apply

locals {
  # Base domain — all hostnames are derived as <service>.<domain> in each module's locals.tf
  domain = "lab.toastdog.net"

  # Kubernetes networking — used in NetworkPolicy ipBlock rules.
  # control_plane_ips: post-DNAT target for egress to the Kubernetes API server (port 6443)
  # cluster_cidr:      webhook ingress source — kube-apiserver webhook calls traverse Calico
  #                    IPIP tunnels, so the source IP at the destination pod is the control
  #                    plane's tunl0 address (within the pod CIDR), not the node IP
  control_plane_ips = ["192.168.30.150"]
  cluster_cidr      = "10.244.0.0/16"

  kubeconfig_path = "~/.kube/config"
}

inputs = {
  domain            = local.domain
  control_plane_ips = local.control_plane_ips
  cluster_cidr      = local.cluster_cidr
  kubeconfig_path   = local.kubeconfig_path
}

# Each module gets its own state file under .terraform-state/
# Paths: .terraform-state/core/, .terraform-state/vault/, .terraform-state/argocd/
remote_state {
  backend = "local"
  config = {
    path = "${get_parent_terragrunt_dir()}/.terraform-state/${path_relative_to_include()}/terraform.tfstate"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# Shared variable declarations — emitted as shared_vars.tf into every child module.
# These four variables are injected by the inputs block below and must be declared
# in every module. Centralizing them here avoids copy-paste across all vars.tf files.
generate "shared_vars" {
  path      = "shared_vars.tf"
  if_exists = "overwrite"
  contents  = <<-EOF
    # Generated by root terragrunt.hcl — do not edit directly.
    # Module-specific variables belong in each module's vars.tf.

    variable "domain" {
      description = "Base domain for all services. Hostnames are derived as <service>.<domain> in locals.tf."
      type        = string
    }

    variable "kubeconfig_path" {
      description = "Path to the kubeconfig file."
      type        = string
      default     = "~/.kube/config"
    }

    variable "control_plane_ips" {
      description = "List of control plane node IPs — used in NetworkPolicy egress rules to allow API server access."
      type        = list(string)
    }

    variable "cluster_cidr" {
      description = "Pod CIDR for the cluster — used in webhook ingress rules."
      type        = string
    }
  EOF
}

# Shared provider version constraints — emitted as versions.tf into every child module.
# This is the single source of truth for all provider versions.
#
# The vault provider is declared here even though only vault/ uses it. Terraform only
# initializes a provider when a provider {} block is configured in that module, so
# non-vault modules incur no runtime cost from the declaration.
#
# Renovate note: versions here are picked up by the custom regex manager in renovate.json
# that scans terragrunt.hcl files. The generated versions.tf files are gitignored.
generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Generated by root terragrunt.hcl — do not edit directly.
    # Update provider versions in kubernetes-terraform/root.hcl instead.
    terraform {
      required_providers {
        helm = {
          source  = "hashicorp/helm"
          version = "~> 3.1.1"  # renovate: datasource=terraform-provider depName=hashicorp/helm
        }
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 3.1.0"  # renovate: datasource=terraform-provider depName=hashicorp/kubernetes
        }
        vault = {
          source  = "hashicorp/vault"
          version = "~> 5.0"  # renovate: datasource=terraform-provider depName=hashicorp/vault
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 3.8"  # renovate: datasource=terraform-provider depName=hashicorp/random
        }
      }
    }
  EOF
}
