global:
  domain: ${argocd_hostname}
  env:
    - name: TZ
      value: America/Los_Angeles

configs:
  params:
    # Traefik handles TLS termination; ArgoCD server runs in HTTP mode
    server.insecure: true

repoServer:
  livenessProbe:
    timeoutSeconds: 10
