# Generated by root terragrunt.hcl at runtime — do not edit directly.
# Subset declared here so IDEs don't flag usages as undeclared variables.

variable "domain" {
  description = "Base domain for all services. Hostnames are derived as <service>.<domain> in locals.tf."
  type        = string
}
