# Generated by root terragrunt.hcl — do not edit directly.
# Module-specific variables belong in each module's vars.tf.

variable "domain" {
  description = "Base domain for all services. Hostnames are derived as <service>.<domain> in locals.tf."
  type        = string
}

variable "kubeconfig_path" {
  description = "Path to the kubeconfig file."
  type        = string
  default     = "~/.kube/config"
}
