# Generated by root terragrunt.hcl — do not edit directly.
# Module-specific variables belong in each module's vars.tf.

variable "kubeconfig_path" {
  description = "Path to the kubeconfig file."
  type        = string
  default     = "~/.kube/config"
}
